#!/bin/bash
# Modify a file, add it to dvcs and commit
DVCS=$1
MODS=$2
LINES=$3
FILENAME=file.txt
for ((i = 0; i < $MODS; i++)); do
	createfile $FILENAME $i $LINES
	if [ "$DVCS" == "git" ]; then 
		$DVCS add $FILENAME
	fi
	echo "Committing $i/$MODS"
	$DVCS commit -m "Committing $i"
done

